eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${LINUX_MACHINE_IP:localhost}:8761/eureka/        # ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    instance:
      hostname: ${LINUX_MACHINE_IP:localhost}
